apiVersion: v1
kind: Service
metadata:
  name: graylog
  labels:
    component: graylog
    type: cluster
spec:
  type: LoadBalancer
  selector:
    component: graylog
    type: cluster
  ports:
  - name: graylog
    port: 9000
    protocol: TCP
